# Generated by Django 5.1.3 on 2025-08-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoOzet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='video_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
