# Generated by Django 5.1.3 on 2025-08-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoOzet', '0002_chatsession_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='transcript_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
