# Generated by Django 5.1.3 on 2025-08-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoOzet', '0003_chatsession_transcript_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='summary_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
