# Generated by Django 5.1.3 on 2025-08-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VideoOzet', '0004_chatsession_summary_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='summary_text',
        ),
    ]
