# Generated by Django 5.1.3 on 2025-08-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoOzet', '0005_remove_chatsession_summary_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
